spring.application.name=Let-s-Go-Cab

spring.datasource.url=jdbc:mysql://localhost:3306/lets_go_cab
spring.datasource.username=root
spring.datasource.password=#Rahul2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=LetsGoCabSecretKey12345
jwt.expiration=86400000
# 1 day in milliseconds

razorpay.key=rzp_test_yWP9QUPN3BnLgH
razorpay.secret=2tfLimfp1DgpnjrZB9rXb5nP

logging.level.org.springframework.security=DEBUG

